#!/bin/sh

set -e

script/build
bundle exec htmlproofer _site \
	--disable-external \
	--no-enforce-https \
	--checks=Images,Links,Scripts,OpenGraph \
	--ignore_urls "/apple-touch-icon/,/favicon/,/site.webmanifest/"
bundle exec rubocop -S -D -E
gem build retlab.gemspec
