#!/bin/bash

set -ex

npx npm-check-updates -u
bundle update
npm update

bundle exec rougify style base16.light | bundle exec sass-convert --stdin --from css --to scss > sass/_base16.light.scss
bundle exec rougify style base16.dark | bundle exec sass-convert --stdin --from css --to scss > sass/_base16.dark.scss
